version: '3'
services:
  tesla-mysql:
    container_name: tesla-mysql
    image: mysql:5.6.36
    ports:
    - 3306:3306
    environment:
    - MYSQL_DATABASE=gateway
    - MYSQL_PASSWORD=root
    - MYSQL_ROOT_PASSWORD=123
    restart: always
  tesla-ops:
    container_name: tesla-ops
    image: tesla-ops:1.0.0
    depends_on:
    - tesla-mysql
    ports:
    - 8080:8080
    environment:
    - DATABASE_HOST=tesla-mysql
    - DATABASE_USER=root
    - DATABASE_PASSWORD=123
    - DATABASE_NAME=gateway
    - DATABASE_PORT=3306
    restart: always
  tesla-gateway:
    container_name: tesla-gateway
    image: tesla-gateway:1.0.0
    depends_on:
    - tesla-mysql
    ports:
    - 8181:8181
    environment:
    - DATABASE_HOST=tesla-mysql
    - DATABASE_USER=root
    - DATABASE_PASSWORD=123
    - DATABASE_NAME=gateway
    - DATABASE_PORT=3306
    extra_hosts:
    - consul:10.12.128.89
    - zookeeper:10.12.128.89
    restart: always