global:
  scrape_interval: 60s
  evaluation_interval: 60s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
    labels:
      instance: prometheus
- job_name: gateway
  static_configs:
  - targets:
    - 10.12.128.89:9001
    labels:
      instance: gateway