server:
  port: 1202
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://eureka.springcloud.cn/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
spring:
  application:
    name: tesla