spring:
  application:
    name: Tesla
  profiles:
    active: dev
  metrics:
    servo:
      enabled: false
server:
  port: 9000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:META-INF/mybatis/**/*Mapper.xml
dubbo:
  registryAddress: zookeeper://127.0.0.1:2181
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/